NAME = 'App Name'
ID = 'AppName'
PACKAGE_ID = 'appname'
VERSION = '1.0'
VERSION_CODE = 1
VERSION_DATE = '01/01/2022'
MAIN_EXE = 'App.exe'
MAIN_BIN = "App"
ICON = "./App.png" # 512x512 PNG image
LINUX_MAINTAINER = "Raouf Ould Ali <raouf@eclipium.xyz>"
DESCRIPTION = "A simple test program"
WEBSITE = "https://github.com/SpeedCode210/SmartPackager"
POSTINST_SCRIPT = False
POSTINST_COMMANDS = ''''''
CATEGORIES = "Game;"
RPM_GROUP = "Games"
LICENSE = "LGPL"
KEYWORDS = "game;arcade;"
